# Generated by Django 5.0.4 on 2024-06-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='title',
            new_name='account_holder',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='content',
        ),
        migrations.AddField(
            model_name='bill',
            name='account_number',
            field=models.CharField(default='00-00-0000', max_length=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_address',
            field=models.CharField(default='', max_length=120),
        ),
    ]
