# Generated by Django 5.0.4 on 2024-06-03 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_current_bill_bill_current_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='period_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
