# Generated by Django 5.0.4 on 2024-06-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bill_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='author',
        ),
    ]
