# Generated by Django 5.0.4 on 2024-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bill_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
