# Generated by Django 5.0.4 on 2024-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bill_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
    ]
